#
# Copyright Siemens AG, 2017. Part of the SW360 Portal Project.
#
# All rights reserved. This configuration file is provided to you under the
# terms and conditions of the Eclipse Distribution License v1.0 which
# accompanies this distribution, and is available at
# http://www.eclipse.org/org/documents/edl-v10.php
#

server:
  port: 8090

sw360:
  sw360-portal-server-url: ${SW360_PORTAL_SERVER_URL:http://127.0.0.1:8080}
  sw360-liferay-company-id: ${SW360_LIFERAY_COMPANY_ID:20155}
  cors:
    allowed-origin: ${SW360_CORS_ALLOWED_ORIGIN:#{null}}

security:
  oauth2:
    resource:
      id: sw360-REST-API
    client:
      client-id: trusted-sw360-client
      client-secret: sw360-secret
      resource-ids: sw360-REST-API
      authorized-grant-types: client_credentials,password
      access-token-validity-seconds: 3600
      scope: all
